# Generated by Django 5.1.3 on 2024-12-15 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('role', models.CharField(default='user', max_length=100)),
            ],
        ),
    ]
