# Generated by Django 5.1.3 on 2024-12-23 04:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default='', editable=False)),
                ('company_id', models.UUIDField(default='', editable=False)),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('role', models.CharField(default='user', max_length=100)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('business_name', models.CharField(max_length=100)),
                ('business_street_address', models.CharField(max_length=200)),
                ('business_registered_country', models.CharField(max_length=100)),
                ('business_registered_city', models.CharField(max_length=100)),
                ('business_registered_zipcode', models.CharField(max_length=100)),
                ('business_contact_number', models.CharField(max_length=100)),
                ('business_email', models.CharField(max_length=100, null=True)),
                ('business_fax_number', models.CharField(max_length=100)),
                ('business_type', models.CharField(default='retail', max_length=100)),
                ('business_size', models.FloatField()),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('business_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usermodel')),
            ],
        ),
    ]
