# Generated by Django 5.1.3 on 2024-12-25 01:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default='', editable=False)),
                ('company_id', models.UUIDField(default='', editable=False)),
                ('status', models.CharField(default='active', max_length=10)),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
