# Generated by Django 5.1.3 on 2024-12-20 04:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('business_name', models.CharField(max_length=100)),
                ('business_street_address', models.CharField(max_length=200)),
                ('business_registered_country', models.CharField(max_length=100)),
                ('business_registered_city', models.CharField(max_length=100)),
                ('business_registered_zipcode', models.CharField(max_length=100)),
                ('business_contact_number', models.CharField(max_length=100)),
                ('business_email', models.CharField(max_length=100, null=True)),
                ('business_fax_number', models.CharField(max_length=100)),
                ('business_type', models.CharField(default='retail', max_length=100)),
                ('business_size', models.FloatField()),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('business_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usermodel')),
            ],
        ),
    ]
