# Generated by Django 5.1.3 on 2024-12-22 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_business_ownder_companymodel_business_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default='', editable=False)),
                ('company_id', models.UUIDField(default='', editable=False)),
                ('timestamp', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
