# Generated by Django 5.1.3 on 2025-01-20 00:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryFilesModel',
            fields=[
                ('file', models.FileField(upload_to='uploads/')),
                ('business_id', models.UUIDField(default=uuid.uuid4)),
                ('presigned_url', models.CharField(max_length=2000, null=True)),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='stripe_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
